export enum Dialogue {
  HELLO = 0,
  WELCOME = 1,
  REPETITION = 2,
  GOODBYE = 3,
  CANNOT = 4,
  NOTFOUND = 5,
  APOLOGISE = 6,
  BECAUSE = 7,
  ALWAYS = 8,
  MAYBE = 9,
  ITHINK = 10,
  YOU = 11,
  NOTCLEAR = 12,
  NO = 13,
  FEEL = 14,
  IAM = 15,
  FAMILY = 16,
  FRIENDS = 17,
  LONELY = 18,
  DREAMED = 19,
  SECONDHELLO = 20,
  NEED = 21,
  REALLYTHINK = 22,
  REMEMBER = 23,
  IF = 24,
  NAME = 25,
  COMPUTER = 26,
  AREYOU = 27,
  IAMBORED = 28,
  THEYARE = 29,
  YOUR = 30,
  WASI = 31,
  DESIRE = 32,
  IAMSAD = 33,
  IAMHAPPY = 34,
  SWEAR = 35,
  ORAL = 36,
  HATE = 37,
  CERTAIN = 38,
  ELABORATE = 39,
  LAST = 40,
}

export const dialogueTranslation = {
  [Dialogue.HELLO]: "My name is Eliza what's yours?",
  [Dialogue.WELCOME]: 'Hello friend. How may I help you?',
  [Dialogue.REPETITION]: 'You seem to be repeating yourself?',
  [Dialogue.CANNOT]: 'What would it take for you to ...?',
  [Dialogue.NOTFOUND]: 'What does that suggest to you?',
  [Dialogue.APOLOGISE]: "Please don't apologize.",
  [Dialogue.BECAUSE]: 'Is that the real reason?',
  [Dialogue.ALWAYS]: 'Can you think of a specific example?',
  [Dialogue.MAYBE]: "You don't seem very certain.",
  [Dialogue.ITHINK]: 'Do you really think so?',
  [Dialogue.YOU]: 'We were discussing you, not me.',
  [Dialogue.NO]: 'Why not?',
  [Dialogue.FEEL]: 'Tell me more about such feelings.',
  [Dialogue.IAM]: 'I am sorry to hear you are ...',
  [Dialogue.FAMILY]: 'Tell me more about your family.',
  [Dialogue.FRIENDS]: 'Tell me more about your friends.',
  [Dialogue.LONELY]: 'Do you often feel lonely?',
  [Dialogue.DREAMED]: 'What does that dream suggest to you?',
  [Dialogue.SECONDHELLO]: 'Hi again! How is it going?',
  [Dialogue.NEED]: 'Why do you need ...?',
  [Dialogue.REALLYTHINK]: "Do you really think I don't ...?",
  [Dialogue.REMEMBER]: 'What else do you recollect?',
  [Dialogue.IF]: "Do you think it's likely that ...?",
  [Dialogue.NAME]: 'I am not interested in names.',
  [Dialogue.COMPUTER]: 'Do computers worry you?',
  [Dialogue.AREYOU]: 'Why are you interested in whether I am ... or not?',
  [Dialogue.THEYARE]: 'Did you think they might not be ...?',
  [Dialogue.YOUR]: 'Why are you concerned over my ...?',
  [Dialogue.WASI]: 'What if you were ...?',
  [Dialogue.DESIRE]: 'Why do you want it?',
  [Dialogue.IAMSAD]: 'Sorry to hear. Tell me about it.',
  [Dialogue.IAMHAPPY]: "That's good. What is making you happy?",
  [Dialogue.IAMBORED]: 'What makes you bored?',
  [Dialogue.GOODBYE]: 'Goodbye. Thank you for talking to me.',
  [Dialogue.SWEAR]: 'Please try to use respectful language.',
  [Dialogue.ORAL]: 'Have you considered you might have an oral fixation?',
  [Dialogue.HATE]: 'Try not to let your anger control you.',
  [Dialogue.CERTAIN]: 'You seem quite sure of this?',
  [Dialogue.ELABORATE]: 'It might help to respond with more than a single word.',
  [Dialogue.NOTCLEAR]: 'My apologies, I sometimes get confused.'
};
